### ISSUE TITLE
Create "Make a Donation - Next Steps" Page for Donator View

### ISSUE THREAD

**Issue by ObjectJosh** [hack4impact-calpoly/habitat-for-humanity#14]
### Description
Create the "Make a Donation - Next Steps" screen based on [Figma](https://www.figma.com/file/MNRQAXLXzBqCR3aRZmXg0T/Habitat-for-Humanity). Don't worry about the navbar at the top for this task (this will be assigned in a separate issue). For this screen, please reuse this component: 
<img width="307" alt="Screen Shot 2022-01-08 at 6 06 10 PM" src="https://user-images.githubusercontent.com/42549561/148666407-4cd93aee-cd4d-462f-9ce0-477e791d340a.png">

 and adjust it according to your screen on Figma, instead of coding it from scratch. Check the Figma to see which screen you may be able to get it from! _(Hint: it's also in the donator view)_ The component _should_ be completed by the time you start this task... but if not, just leave said component blank and let me know in a comment when submitting the pull request.

### Setup
1. Navigate to `/frontend/src/components/`
2. Create a folder named "donation" _(if it already exists, skip this step)_
3. Navigate into that folder named "donation"
4. Create a folder with the [PascalCase](https://techterms.com/definition/pascalcase) naming convention (name based on the component you're working on)
5. Inside the folder, create a `.tsx` file with the same name as the folder
6. Be sure to update the `App.js` file with your new component, or else you wont see any changes you make. This file is located in `/frontend/src/`

### Success Metrics Checklist
- [x] Looks exactly like the Figma (again, disregarding the navbar)
- [x] Responsive screen handling
- [x] Prompt user to make a call when phone number is clicked (Refer to the functionality of [their website](https://hfhsloco.org/)'s contact section at the bottom)

Finally, on your pull request, please request a code review from me (@ObjectJosh)

<img width="518" alt="Screen Shot 2022-01-08 at 6 07 13 PM" src="https://user-images.githubusercontent.com/42549561/148666423-88489160-1f6d-496b-8ac8-d1bcce30b9fc.png">

**Comment by spencersablan** [comment]
@ObjectJosh Hey Josh!  Is the navbar you're talking about here the header?  Or the progress bar that sits above the next steps?
