### ISSUE TITLE
Create "Profile - Edit" Page for Donator View

### ISSUE THREAD

**Issue by ObjectJosh** [hack4impact-calpoly/habitat-for-humanity#42]
### Description
Create the "Profile - Edit" screen based on [Figma](https://www.figma.com/file/MNRQAXLXzBqCR3aRZmXg0T/Habitat-for-Humanity). Don't worry about the navbar at the top for this task (this was assigned in a separate issue).

### Setup
1. Navigate to `/frontend/src/components/`
2. Create a folder named "profile" _(if it already exists, skip this step)_
3. Navigate into that folder named "profile"
4. Create a folder with the [PascalCase](https://techterms.com/definition/pascalcase) naming convention (name based on the component you're working on)
5. Inside the folder, create a `.tsx` file with the same name as the folder
6. Be sure to update the `App.js` file with your new component, or else you wont see any changes you make. This file is located in `/frontend/src/`

### Success Metrics Checklist
- [ ] Looks exactly like the Figma (again, disregarding the navbar)
- [ ] Responsive screen handling
- [ ] Error pops up for invalid/empty input field
- [ ] Cursor changes on hover for buttons
- [ ] Store submitted input into state variable

Finally, on your pull request, please request a code review from me (@ObjectJosh)

<img width="602" alt="Screen Shot 2022-01-19 at 10 42 16 PM" src="https://user-images.githubusercontent.com/42549561/150287033-6c37cf17-55fa-4abf-999a-f6ae7c764553.png">

**Comment by scallait** [comment]
@ObjectJosh I believe this page has already been created in another [issue](https://github.com/hack4impact-calpoly/habitat-for-humanity/pull/32).
