### ISSUE TITLE
Mobile "Create An Account" Page View

### ISSUE THREAD

**Issue by ObjectJosh** [hack4impact-calpoly/habitat-for-humanity#44]
### Description
Responsively switch to mobile view for "Create An Account" page based on [Figma](https://www.figma.com/file/MNRQAXLXzBqCR3aRZmXg0T/Habitat-for-Humanity).
(Screens less than 640px width)

### Success Metrics Checklist
- [x] Looks exactly like the Figma

Finally, on your pull request, please request a code review from me (@ObjectJosh)

<img width="174" alt="Screen Shot 2022-01-19 at 10 53 58 PM" src="https://user-images.githubusercontent.com/42549561/150288501-09419310-421f-41ab-8236-4301b2dea7c0.png">

**Comment by scallait** [comment]
Issue completed and merged into dev
